In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\imraj\\Downloads\\bank_note_auth.csv")
df

      variance      skew  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [3]:
df.isnull().sum()

variance    0
skew        0
curtosis    0
entropy     0
class       0
dtype: int64

In [4]:
x=df.drop(columns="class")
y=df["class"]

In [5]:
x[:5]

   variance    skew  curtosis  entropy
0   3.62160  8.6661   -2.8073 -0.44699
1   4.54590  8.1674   -2.4586 -1.46210
2   3.86600 -2.6383    1.9242  0.10645
3   3.45660  9.5228   -4.0112 -3.59440
4   0.32924 -4.4552    4.5718 -0.98880

In [6]:
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [8]:
len(x_train)

1097

In [9]:
len(x_test)

275

In [10]:
x_train[:5]

      variance     skew  curtosis   entropy
1226   -4.0679   2.4955   0.79571 -1.103900
1085   -2.6649 -12.8130  12.66890 -1.908200
148     3.6277   0.9829   0.68861  0.634030
1178   -2.0754   1.2767  -0.64206 -1.264200
478    -1.7781   0.8546   7.13030  0.027572

In [11]:
x_test[:5]

      variance     skew   curtosis  entropy
1240   -3.5510  1.89550   0.186500 -2.44090
703     1.3114  4.54620   2.293500  0.22541
821    -4.0173 -8.31230  12.454700 -1.43750
1081   -5.1190  6.64860  -0.049987 -6.52060
37      3.6289  0.81322   1.627700  0.77627

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [13]:
x_train[:5]

array([[-1.58438248,  0.1072115 , -0.14276339,  0.03334576],
       [-1.08829139, -2.53123321,  2.67783284, -0.35092979],
       [ 1.13672843, -0.15348755, -0.16820608,  0.86368769],
       [-0.87984827, -0.10285065, -0.48432018, -0.04324179],
       [-0.77472505, -0.17560027,  1.36208246,  0.57393637]])

In [14]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [15]:
y_test[:20]

1240    1
703     0
821     1
1081    1
37      0
167     0
223     0
647     0
325     0
558     0
341     0
1218    1
302     0
1124    1
793     1
80      0
607     0
538     0
255     0
236     0
Name: class, dtype: int64

In [16]:
y_test_pred=classifier.predict(x_test)

In [17]:
y_test_pred[:20]

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0])

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,y_test_pred)

0.9963636363636363

In [20]:
import joblib

In [21]:
joblib.dump(classifier,"Classifier.pkl")

['Classifier.pkl']

In [22]:
joblib.dump(scaler,"Scaler.pkl")

['Scaler.pkl']